global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'opentelemetry'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'host.docker.internal:8889' ]